name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  quality:
    uses: ./.github/workflows/code-quality.yml

  preview:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Dependencies
        working-directory: frontend
        run: pnpm install

      - name: Build
        working-directory: frontend
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_PATH: /pr-preview/${{ github.event.pull_request.number }}
        run: pnpm build

      - name: Deploy Preview
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/out
          branch: gh-pages
          target-folder: pr-preview/${{ github.event.pull_request.number }}
          clean: true

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Preview deployment

      - name: Comment PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            📝 Preview deployment is ready!
            URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-preview/${{ github.event.pull_request.number }}/
            
            _Last updated: ${{ github.event.pull_request.updated_at }}_
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
